# version: "3.8"

services:
  minio:
    image: minio/minio:latest # dockerhub 사용
    container_name: minio
    # restart: always
    ports:
      - "9000:9000" # 파일 업로드 다운로드 포트. S3 API와 연결 가능 (외부 서버와 통신을 위한 개방)
      - "9001:9001" # WebUI 사용 포트
    env_file:
      - /home/yewon/job-interview-data/.env # 경로 직접 지정
    volumes:
      - /home/yewon/job-interview-data/setting_object_storage/stand-alone/minio-data:/data # 윈도우의 minio-data폴더를 minio의 /data로 마운트
    # server /data: MinIO 서버를 실행하면서, 컨테이너 내부의 /data 디렉토리를 스토리지 경로로 사용한다
    # --console-adress: 웹 콘솔을 9001번 포트에서 실행
    # --adress: 외부 통신을 9000번 포트에서 실행
    command: server /data --address ":9000" --console-address ":9001"

    # networks:
    #   - minio-net

# volumes:
#  minio_data:
#    external: true
